-- Savour v52 admin + privacy-conscious first-party analytics
-- Run this once in Supabase SQL Editor.

create table if not exists public.savour_admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.savour_admin_users enable row level security;

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  path text not null default '/',
  referrer text,
  user_agent text,
  visited_at timestamptz not null default now()
);

create index if not exists site_visits_visited_at_idx on public.site_visits(visited_at desc);
create index if not exists site_visits_visitor_id_idx on public.site_visits(visitor_id);
alter table public.site_visits enable row level security;

drop policy if exists "site visits insert" on public.site_visits;
create policy "site visits insert" on public.site_visits
for insert to anon, authenticated with check (true);

create or replace function public.claim_savour_admin()
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then return false; end if;
  if lower(coalesce(auth.jwt()->>'email','')) <> 'schreurs.jop@gmail.com' then return false; end if;
  insert into public.savour_admin_users(user_id) values (auth.uid()) on conflict (user_id) do nothing;
  return true;
end;
$$;

grant execute on function public.claim_savour_admin() to authenticated;

create or replace function public.is_savour_admin()
returns boolean
language sql
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.savour_admin_users a
    where a.user_id = auth.uid()
  );
$$;

grant execute on function public.is_savour_admin() to authenticated;

create or replace function public.get_savour_admin_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  out jsonb;
begin
  if not exists (select 1 from public.savour_admin_users where user_id = auth.uid()) then
    raise exception 'not authorized';
  end if;

  select jsonb_build_object(
    'accounts', (select count(*) from auth.users),
    'recipes', (select count(*) from public.recipes),
    'folders', (select count(*) from public.folders),
    'shared_maps', (select count(*) from public.shared_maps),
    'visits_today', (select count(distinct visitor_id) from public.site_visits where visited_at >= date_trunc('day', now())),
    'visits_week', (select count(distinct visitor_id) from public.site_visits where visited_at >= date_trunc('week', now())),
    'visits_month', (select count(distinct visitor_id) from public.site_visits where visited_at >= date_trunc('month', now())),
    'accounts_list', coalesce((select jsonb_agg(x order by x.created_at desc) from (
      select u.id, u.email, u.created_at, u.last_sign_in_at,
             coalesce(nullif(p.name,''), split_part(coalesce(u.email,''),'@',1)) as name
      from auth.users u
      left join public.profiles p on p.id=u.id
      order by u.created_at desc limit 100
    ) x), '[]'::jsonb),
    'recent_visits', coalesce((select jsonb_agg(x order by x.visited_at desc) from (
      select visited_at, path, referrer, user_agent
      from public.site_visits
      order by visited_at desc limit 100
    ) x), '[]'::jsonb),
    'account_growth', coalesce((select jsonb_agg(jsonb_build_object('label',label,'count',count) order by day) from (
      select date_trunc('day', created_at)::date as day,
             to_char(date_trunc('day', created_at),'DD/MM') as label,
             count(*)::int as count
      from auth.users
      where created_at >= now() - interval '14 days'
      group by 1,2
    ) x), '[]'::jsonb)
  ) into out;
  return out;
end;
$$;

grant execute on function public.get_savour_admin_dashboard() to authenticated;

-- The first time the admin signs in at /admin, the frontend calls claim_savour_admin.
-- This binds admin access to the exact authenticated email above; the password is never stored in the app code.
